name = "fotox-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "fotox"

[vars]
PUBLIC_BASE_URL = "https://your-worker.workers.dev"
R2_PUBLIC_BASE_URL = ""
